name: Publish on Release created

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci

      - name: Publish on NPM
        run: npm publish

  publish-github:
    name: Publish on GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          registry-url: https://npm.pkg.github.com/
          scope: "@GreepTheSheep"
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci

      - name: Set package scope for GitHub Packages
        run: |
          npm pkg set name="@GreepTheSheep/tm-essentials"
          npm pkg set publishConfig.registry="https://npm.pkg.github.com"

      - name: Publish on GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}